import { Link } from 'react-router-dom'
import { ArrowLeft, Shield, AlertCircle, CheckCircle, FileText } from 'lucide-react'

function TermsOfService() {
  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <div className="bg-white border-b border-gray-200">
        <div className="max-w-4xl mx-auto px-4 py-6">
          <Link to="/" className="flex items-center gap-2 text-gray-600 hover:text-gray-900 mb-4">
            <ArrowLeft className="w-5 h-5" />
            Back to Home
          </Link>
          <div className="flex items-center gap-3">
            <div className="w-12 h-12 bg-primary-100 rounded-xl flex items-center justify-center">
              <Shield className="w-6 h-6 text-primary-600" />
            </div>
            <div>
              <h1 className="text-3xl font-bold text-gray-900">Terms of Service</h1>
              <p className="text-gray-600">Last updated: January 21, 2026</p>
            </div>
          </div>
        </div>
      </div>

      {/* Content */}
      <div className="max-w-4xl mx-auto px-4 py-12">
        <div className="bg-white rounded-2xl shadow-sm border border-gray-200 p-8 space-y-8">
          
          {/* Introduction */}
          <section>
            <p className="text-gray-700 leading-relaxed">
              Welcome to Job Agent ("we," "our," or "us"). By accessing or using our service, 
              you agree to be bound by these Terms of Service. Please read them carefully.
            </p>
          </section>

          {/* 1. Service Description */}
          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4 flex items-center gap-2">
              <FileText className="w-6 h-6 text-primary-600" />
              1. Service Description
            </h2>
            <div className="space-y-3 text-gray-700">
              <p>
                Job Agent provides AI-powered job application analysis services, including:
              </p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>CV and job description matching analysis</li>
                <li>ATS (Applicant Tracking System) compatibility scoring</li>
                <li>Cover letter and application materials generation</li>
                <li>Job application tracking and management</li>
              </ul>
            </div>
          </section>

          {/* 2. Important Disclaimer */}
          <section className="bg-yellow-50 border-2 border-yellow-300 rounded-xl p-6">
            <h2 className="text-2xl font-bold text-gray-900 mb-4 flex items-center gap-2">
              <AlertCircle className="w-6 h-6 text-yellow-600" />
              2. Important Disclaimer
            </h2>
            <div className="space-y-3 text-gray-700">
              <p className="font-semibold text-yellow-900">
                Please read this section carefully as it limits our liability:
              </p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>
                  <strong>No Hiring Guarantees:</strong> Job Agent provides AI-generated insights 
                  and analysis for informational purposes only. We do not guarantee job offers, 
                  interviews, or any hiring outcomes.
                </li>
                <li>
                  <strong>Not Career Advice:</strong> Our service is not a substitute for professional 
                  career counseling or recruitment services.
                </li>
                <li>
                  <strong>ATS Results Not Guaranteed:</strong> While we analyze ATS compatibility, 
                  actual ATS systems vary widely and results may differ from our predictions.
                </li>
                <li>
                  <strong>AI-Generated Content:</strong> All content generated by our AI (cover letters, 
                  answers, etc.) should be reviewed and customized by you before submission.
                </li>
                <li>
                  <strong>No Liability for Outcomes:</strong> We are not responsible for the results 
                  of your job applications, including rejections or hiring decisions.
                </li>
              </ul>
            </div>
          </section>

          {/* 3. Credit System */}
          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">
              3. Credit System & Billing
            </h2>
            <div className="space-y-4 text-gray-700">
              <div>
                <h3 className="font-semibold text-gray-900 mb-2">3.1 How Credits Work</h3>
                <ul className="list-disc list-inside space-y-2 ml-4">
                  <li>Job analysis requires 1 credit per job</li>
                  <li>Credits are deducted when analysis begins</li>
                  <li>Unused credits do not expire (except for free tier monthly resets)</li>
                  <li>Credits are non-transferable between accounts</li>
                </ul>
              </div>

              <div>
                <h3 className="font-semibold text-gray-900 mb-2">3.2 Refund Policy</h3>
                <ul className="list-disc list-inside space-y-2 ml-4">
                  <li>
                    <strong>Analysis Failures:</strong> If an analysis fails due to a technical error 
                    on our end, the credit will be automatically refunded.
                  </li>
                  <li>
                    <strong>Subscription Refunds:</strong> We offer a 7-day money-back guarantee for 
                    new subscriptions. Contact jobagentcareers@gmail.com within 7 days.
                  </li>
                  <li>
                    <strong>Credit Purchases:</strong> Credit purchases are non-refundable unless 
                    there is a technical error preventing service delivery.
                  </li>
                  <li>
                    <strong>Per-Job Unlocks:</strong> Premium job unlocks (£2.99) are non-refundable 
                    once the analysis is unlocked and viewed.
                  </li>
                </ul>
              </div>

              <div>
                <h3 className="font-semibold text-gray-900 mb-2">3.3 Subscription Management</h3>
                <ul className="list-disc list-inside space-y-2 ml-4">
                  <li>Subscriptions auto-renew unless cancelled</li>
                  <li>Cancel anytime via your billing dashboard</li>
                  <li>Cancellation takes effect at the end of the current billing period</li>
                  <li>No partial refunds for unused subscription time</li>
                </ul>
              </div>
            </div>
          </section>

          {/* 4. Fair Usage Policy */}
          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">
              4. Fair Usage & Prohibited Activities
            </h2>
            <div className="space-y-4 text-gray-700">
              <p>You agree NOT to:</p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>Use automated scripts, bots, or scrapers to access our service</li>
                <li>Submit spam, duplicate, or fake job descriptions for analysis</li>
                <li>Share your account credentials with others</li>
                <li>Reverse engineer, decompile, or attempt to extract our AI models</li>
                <li>Use the service for any illegal or unauthorized purpose</li>
                <li>Abuse our support system or submit fraudulent refund requests</li>
                <li>Resell, redistribute, or sublicense our service</li>
              </ul>
              <p className="mt-4">
                <strong>Violations may result in:</strong> Account suspension, termination, 
                and forfeiture of remaining credits without refund.
              </p>
            </div>
          </section>

          {/* 5. Data Handling */}
          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">
              5. Your Data & Privacy
            </h2>
            <div className="space-y-4 text-gray-700">
              <div className="bg-green-50 border-2 border-green-300 rounded-lg p-4">
                <h3 className="font-semibold text-green-900 mb-2 flex items-center gap-2">
                  <CheckCircle className="w-5 h-5" />
                  What We DO:
                </h3>
                <ul className="list-disc list-inside space-y-1 ml-4 text-green-900">
                  <li>Store your CV and job descriptions to provide our service</li>
                  <li>Use them for analysis and generating application materials</li>
                  <li>Encrypt your data in transit and at rest</li>
                  <li>Allow you to delete your data anytime</li>
                </ul>
              </div>

              <div className="bg-red-50 border-2 border-red-300 rounded-lg p-4">
                <h3 className="font-semibold text-red-900 mb-2 flex items-center gap-2">
                  <AlertCircle className="w-5 h-5" />
                  What We DON'T DO:
                </h3>
                <ul className="list-disc list-inside space-y-1 ml-4 text-red-900">
                  <li>Use your CV or job descriptions to train our AI models</li>
                  <li>Share your personal data with third parties (except payment processors)</li>
                  <li>Sell your data to recruiters or employers</li>
                  <li>Keep your data after you delete your account</li>
                </ul>
              </div>

              <p className="mt-4">
                For more details, see our <Link to="/privacy" className="text-primary-600 hover:underline font-semibold">Privacy Policy</Link>.
              </p>
            </div>
          </section>

          {/* 6. Intellectual Property */}
          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">
              6. Intellectual Property
            </h2>
            <div className="space-y-3 text-gray-700">
              <p>
                <strong>Our Content:</strong> The Job Agent service, including its design, 
                features, and AI models, is our proprietary property. You may not copy, 
                modify, or redistribute it.
              </p>
              <p>
                <strong>Your Content:</strong> You retain all rights to your CV, job descriptions, 
                and other content you upload. By using our service, you grant us a limited license 
                to process this content solely to provide our services.
              </p>
              <p>
                <strong>Generated Content:</strong> AI-generated content (cover letters, answers, etc.) 
                is provided to you for your use. However, you are responsible for reviewing and 
                customizing it before submission.
              </p>
            </div>
          </section>

          {/* 7. Limitation of Liability */}
          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">
              7. Limitation of Liability
            </h2>
            <div className="space-y-3 text-gray-700">
              <p>
                To the maximum extent permitted by law:
              </p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>
                  Job Agent is provided "as is" without warranties of any kind
                </li>
                <li>
                  We are not liable for any indirect, incidental, or consequential damages
                </li>
                <li>
                  Our total liability is limited to the amount you paid in the past 12 months
                </li>
                <li>
                  We are not responsible for third-party services (e.g., Stripe, OpenAI)
                </li>
              </ul>
            </div>
          </section>

          {/* 8. Changes to Terms */}
          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">
              8. Changes to These Terms
            </h2>
            <p className="text-gray-700">
              We may update these Terms from time to time. We will notify you of significant 
              changes via email or a notice on our website. Continued use of the service 
              after changes constitutes acceptance of the new Terms.
            </p>
          </section>

          {/* 9. Termination */}
          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">
              9. Account Termination
            </h2>
            <div className="space-y-3 text-gray-700">
              <p>
                <strong>Your Rights:</strong> You may delete your account at any time through 
                your settings page. All your data will be permanently deleted within 30 days.
              </p>
              <p>
                <strong>Our Rights:</strong> We may suspend or terminate accounts that violate 
                these Terms, engage in abusive behavior, or for legal reasons.
              </p>
            </div>
          </section>

          {/* 10. Governing Law */}
          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">
              10. Governing Law
            </h2>
            <p className="text-gray-700">
              These Terms are governed by the laws of England and Wales. Any disputes shall 
              be subject to the exclusive jurisdiction of the courts of England and Wales.
            </p>
          </section>

          {/* 11. Contact */}
          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">
              11. Contact Us
            </h2>
            <div className="text-gray-700">
              <p className="mb-2">If you have questions about these Terms:</p>
              <ul className="space-y-1">
                <li>📧 Email: <a href="mailto:jobagentcareers@gmail.com" className="text-primary-600 hover:underline">jobagentcareers@gmail.com</a></li>
                <li>🌐 Website: <a href="https://jobagent-career.com" className="text-primary-600 hover:underline">jobagent-career.com</a></li>
              </ul>
            </div>
          </section>

          {/* Acceptance */}
          <section className="bg-primary-50 border-2 border-primary-300 rounded-xl p-6">
            <p className="text-gray-900 font-semibold">
              By creating an account or using Job Agent, you acknowledge that you have read, 
              understood, and agree to be bound by these Terms of Service.
            </p>
          </section>
        </div>

        {/* Quick Links */}
        <div className="mt-8 flex justify-center gap-6">
          <Link to="/privacy" className="text-primary-600 hover:underline font-semibold">
            Privacy Policy →
          </Link>
          <Link to="/" className="text-gray-600 hover:underline">
            Back to Home
          </Link>
        </div>
      </div>
    </div>
  )
}

export default TermsOfService